# -*- coding: utf-8 -*-
"""random_quote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5w2jdSVsabr7lxKcKXCLoQAuyuQznJS
"""

import random

def get_random_quote():
    quotes = [
        "Life is 10% what happens to us and 90% how we react to it.",
        "The best way to predict your future is to create it.",
        "Keep your face always toward the sunshine—and shadows will fall behind you.",
        "It does not matter how slowly you go as long as you do not stop.",
        "You miss 100% of the shots you don't take."
    ]
    return random.choice(quotes)

if __name__ == "__main__":
    quote = get_random_quote()
    print(f"\nRandom Quote:\n\"{quote}\"\n")